### PR TITLE
Fix jfltetmo compilation

### PR DESCRIPTION
**Pull request by Qiangong2**
Building for jfltetmo fails if these packages are not included

### CODE REVIEW

**Comment by Herrie82** [comment]
This seems to be needed for Xiaomi Kenzo as well for the doze feature. There seems to be no easy way delete it using the proprietary-files.txt files, only by commenting out in the .mk and names are random. To avoid people having to patch, might be good to provide it here even though we don't use it? 

On Kenzo I get:
"device/xiaomi/msm8956-common/doze/Android.mk:33: frameworks/base/packages/SettingsLib/common.mk: No such file or directory"

**Comment by Qiangong2** [comment]
On jfltetmo I get:
"device/samsung/qcom-common/doze/Android.mk:37: 
frameworks/base/packages/SettingsLib/common.mk: No such file or directory"

**Review by bhush9 — CHANGES_REQUESTED** [review]
-1, SettingsLib is java library and is not used by android container at all.. You need to comment out doze in your device tree.

**Comment by Qiangong2** [comment]
Yes, but doze requires it and the sensors on our devices require doze to function fully. Yes it will never be fully functional without doze.

**Comment by Herrie82** [comment]
This was solved in the halium-devices/setup script a long time ago:
https://github.com/Halium/halium-devices/blob/halium-7.1/setup#L6

**Pull request closed without merging**
